name: coverage

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: coverage-report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test
          annotations: none
          output: report-markdown
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output report to summary
        run: |
          cat <<EOS >>$GITHUB_STEP_SUMMARY
          ${{ steps.coverage-report.outputs.report }}
          EOS
